/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as SmartSwitchRouteImport } from './routes/smart-switch'
import { Route as ControlPanelJeevaniRouteImport } from './routes/control-panel-jeevani'
import { Route as IndexRouteImport } from './routes/index'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartSwitchRoute = SmartSwitchRouteImport.update({
  id: '/smart-switch',
  path: '/smart-switch',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlPanelJeevaniRoute = ControlPanelJeevaniRouteImport.update({
  id: '/control-panel-jeevani',
  path: '/control-panel-jeevani',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/control-panel-jeevani': typeof ControlPanelJeevaniRoute
  '/smart-switch': typeof SmartSwitchRoute
  '/verify': typeof VerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/control-panel-jeevani': typeof ControlPanelJeevaniRoute
  '/smart-switch': typeof SmartSwitchRoute
  '/verify': typeof VerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/control-panel-jeevani': typeof ControlPanelJeevaniRoute
  '/smart-switch': typeof SmartSwitchRoute
  '/verify': typeof VerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/control-panel-jeevani' | '/smart-switch' | '/verify'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/control-panel-jeevani' | '/smart-switch' | '/verify'
  id: '__root__' | '/' | '/control-panel-jeevani' | '/smart-switch' | '/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ControlPanelJeevaniRoute: typeof ControlPanelJeevaniRoute
  SmartSwitchRoute: typeof SmartSwitchRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-switch': {
      id: '/smart-switch'
      path: '/smart-switch'
      fullPath: '/smart-switch'
      preLoaderRoute: typeof SmartSwitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-panel-jeevani': {
      id: '/control-panel-jeevani'
      path: '/control-panel-jeevani'
      fullPath: '/control-panel-jeevani'
      preLoaderRoute: typeof ControlPanelJeevaniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ControlPanelJeevaniRoute: ControlPanelJeevaniRoute,
  SmartSwitchRoute: SmartSwitchRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
